CREATE TABLE `science-landing.landing.retailer_sales`
(
  BRAND_ID INT64,
  DOOR_KEY STRING,
  PRODUCT_KEY STRING,
  W_E_DATE DATE,
  SELL_THRU_GROSS_UNITS_SOLD INT64,
  SELL_THRU_GROSS_DOLLARS FLOAT64,
  CUSTOMERS_RETURN_UNIT INT64,
  CUSTOMER_RETURN_DOLLARS FLOAT64
)
PARTITION BY W_E_DATE
CLUSTER BY BRAND_ID, DOOR_KEY, PRODUCT_KEY;