CREATE TABLE `science-landing.landing.retailer_products`
(
  BRAND_ID INT64,
  PRODUCT_KEY STRING,
  PRODUCT_DESC STRING,
  SHADE_DESCRIPTION STRING,
  UPC_CODE INT64,
  CURRENT_PRODUCT_KEY STRING,
  INV_CATEGORY_NAME STRING,
  SAP_INVENTORY_TYPE_DESC STRING
);