CREATE TABLE `landing-project.skulytics.sh_macys_retail_media_tbl`
(
  retailer STRING,
  digital_media_type STRING,
  campaign_name STRING,
  brand STRING,
  attribution STRING,
  placement_type STRING,
  line_item STRING,
  spend_bucket STRING,
  tactic STRING,
  month STRING,
  fiscal_year STRING,
  quarter STRING,
  spend STRING,
  impressions STRING,
  clicks STRING,
  ctr STRING,
  cpm STRING,
  cpc STRING,
  aov STRING,
  cvr STRING,
  online_sales_last_click STRING,
  online_roas_last_click STRING,
  new_buyers STRING,
  total_buyers STRING,
  new_buyer_percentage STRING,
  file_date STRING,
  upload_timestamp STRING,
  reload_required STRING
);