CREATE TABLE `science-landing.landing.skai_retailer_products`
(
  REPORT_DATE DATE,
  KEYWORD STRING,
  RETAILER STRING,
  POSITION INT64,
  RESULT_TYPE STRING,
  BRAND STRING,
  TITLE STRING,
  PRODUCT_ID STRING,
  AD_URL STRING
)
PARTITION BY REPORT_DATE;